apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-shop
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/nodejs-shop
#   uid: e628c806-ab0d-4b9c-86d3-89620e45f3d1
#   resourceVersion: '1235186'
#   generation: 11
#   creationTimestamp: '2019-12-24T15:43:15Z'
  labels:
    k8s-app: nodejs-shop
#   annotations:
#     deployment.kubernetes.io/revision: '11'
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: nodejs-shop
  template:
    metadata:
      name: nodejs-shop
      creationTimestamp: null
      labels:
        k8s-app: nodejs-shop
    spec:
      containers:
        - name: nodejs-shop
          image: omrmtn/nodejs-shop
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MONGO_USER
              value: omrmtn
            - name: MONGO_PASSWORD
              value: 5oczxeSFOMzZQH7o
            - name: MONGO_DEFAULT_DATABASE
              value: shop
            - name: STRIPE_KEY
              value: sk_test_CqtJsRu3yLTPqAqylvQqjawd0040zg0ePy
          resources: {}
        #   terminationMessagePath: /dev/termination-log
        #   terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 25%
#       maxSurge: 25%
#   revisionHistoryLimit: 10
#   progressDeadlineSeconds: 600
# status:
#   observedGeneration: 11
#   replicas: 2
#   updatedReplicas: 2
#   readyReplicas: 2
#   availableReplicas: 2
#   conditions:
#     - type: Progressing
#       status: 'True'
#       lastUpdateTime: '2019-12-25T02:24:42Z'
#       lastTransitionTime: '2019-12-25T02:11:07Z'
#       reason: NewReplicaSetAvailable
#       message: ReplicaSet "nodejs-shop-55684d9bd7" has successfully progressed.
#     - type: Available
#       status: 'True'
#       lastUpdateTime: '2020-01-04T02:53:14Z'
#       lastTransitionTime: '2020-01-04T02:53:14Z'
#       reason: MinimumReplicasAvailable
#       message: Deployment has minimum availability.



apiVersion: v1
kind: Service
metadata:
  name: nodejs-shop
  labels:
    k8s: nodejs-shop
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    matchLabels:
      k8s-app: nodejs-shop
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s: mongo
    spec:
      containers:
      - image: omrmtn/mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    matchLabels:
      k8s-app: mongo